apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html
          configMap:
            name: nginx-config
            items:
              - key: index.html
                path: index.html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  index.html: |
    <html>
    <head><title>Argo CD Nginx Demo</title></head>
    <body style="background:#111; color:#0f0; text-align:center;">
      <h1>Welcome to Argo CD Nginx Demo 🚀</h1>
      <p>Deployed via GitOps using Argo CD!</p>
    </body>
    </html>
