apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: nginx-project
  source:
    repoURL: 'https://github.com/umair-devops/argocd-nginx-demo.git'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true       # delete resources not in Git
      selfHeal: true    # fix drift automatically
    syncOptions:
      - CreateNamespace=true
