apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nginx-project
  namespace: argocd
spec:
  description: Project for Nginx Demo
  sourceRepos:
    - '*'
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
